[build]
# here we will use build commands to simulate a static site build
# simple copy/move
  base = "base"
  command = "hugo version ; env ; ./copy-build.sh"
  publish = "post"
  ignore = "false"

[build.environment]
  CI = ""
  ARBITRARY = ""
[context.deploy-preview]

#  command = "  || { sleep 120 ; false ; } "

[context.toml-testing]
  command='true'
  publish='./.'

[[redirects]]
  from = "/foo"
  to = "/bar"
  status = 301

[[redirects]]
  from = "/r/:token"
  to = "https://38aee3bdb3a31cbd3ed5123a894f9b4b.m.pipedream.net/r/:token?id=:ref"
  force = true
  query = {ref = ":ref"}
  status = 301

[[redirects]]
  from = "/s/:token"
  to = "https://38aee3bdb3a31cbd3ed5123a894f9b4b.m.pipedream.net/s/:token?id=:ref"
  force = true
  query = {ref = ":ref"}
  status = 200

